// packages/core barrel: every module in this package is re-exported here with `export *`,
// uniformly, so that anything published from a `.ts` file under src/ is reachable both as a
// named import from '@openpos/core' and as '@openpos/core/<module>'.
//
// Mobile's Metro resolver collapses EVERY '@openpos/core/<module>' subpath onto this file and
// ignores package.json "exports" entirely (see apps/mobile/metro.config.js). A module that
// isn't re-exported here is `undefined` at runtime on a real device even though vitest (Node
// resolution, which does honour package.json exports) resolves it fine and every test passes.
// The uniform `export *` convention below exists specifically to make that bug class impossible:
// a module reachable from src/ is barrel-reachable by construction. Guarded by
// index-exports.test.ts.
//
// One deliberate exception: toStableSyncJson is also exported under its old alias
// toStableJson. This preserves the public name without duplicating its implementation.

export * from './types';
export { isSettingsSyncGroupEnabled } from './settings-options';
export * from './async-utils';
export * from './storage';
export * from './range-selection';
export * from './task-metadata-filter-visibility';
export * from './resolve-feature-flags';
export * from './bulk-organize';
export * from './announcements';
export * from './user-prompts';
export * from './process-inbox-workflow';
export * from './process-inbox-session';
export * from './process-inbox-plan';
export * from './speech-to-task';
export * from './data-transfer-transaction';
export * from './feedback';
export * from './store';
export { nameNotifyListener } from './store-notify-profiler';
export * from './store-types';
export * from './store-helpers';
export * from './sync';
export * from './tombstone-compaction';
export * from './task-date-coherence';
export * from './sync-normalization';
export * from './sync-document';
export * from './sync-helpers';
export { toStableSyncJson as toStableJson } from './sync-helpers'; // preserved alias; the plain name is also re-exported via `export *` above
export * from './sync-log-utils';
export * from './sync-client-helpers';
export * from './sync-runtime-utils';
export * from './sync-orchestrator';
export * from './sync-configuration-transaction';
export * from './sync-service-utils';
export * from './sync-run';
export * from './sync-run-ports';
export * from './sync-payload-trace';
export * from './sync-backend-io';
export * from './sync-fast-sync';
export * from './sync-crypto';
export * from './sync-encryption';
export * from './sync-encryption-diagnostics';
export * from './sync-remote-fence';
export * from './sync-remote-fence-providers';
export * from './diceware';
export * from './task-utils';
export * from './view-sections';
export * from './task-speech';
export * from './completion-grouping';
export * from './filter-criteria';
export * from './task-filter-selections';
export * from './task-draft';
export * from './task-token-usage';
export * from './people';
export * from './bulk-task-tokens';
export * from './contexts';
export * from './i18n';
export * from './i18n/i18n-storage';
export * from './i18n/i18n-loader';
export * from './i18n/i18n-constants';
export * from './recurrence';
export * from './recurrence-constants';
export * from './review-utils';
export * from './project-utils';
export * from './project-grouping';
export * from './focus-utils';
export * from './undo-task-completion';
export * from './uuid';
export * from './date';
export * from './quick-add';
export * from './area-filter';
export * from './area-utils';
export * from './calendar-scheduling';
export * from './calendar-push-run';
export * from './external-calendar-ingestion';
export * from './schedule-utils';
export * from './time-spent';
export * from './digest-utils';
export * from './search';
export * from './saved-filters';
export * from './saved-filter-labels';
export * from './hierarchy-utils';
export * from './markdown';
export * from './obsidian-parser';
export * from './tasknotes-parser';
export * from './webdav';
export * from './webdav-attachment-inventory';
export * from './cloud';
export * from './http-utils';
export * from './retry-utils';
export * from './async-queue';
export * from './attachment-hash';
export * from './attachment-link-utils';
export * from './cloudkit-attachments';
export * from './attachment-validation';
export * from './attachment-change-detection';
export * from './attachment-progress';
export * from './attachment-transfer';
export * from './attachment-presence-repair';
export * from './attachment-paths';
export * from './attachment-draft-settlement';
export * from './attachment-cleanup';
export * from './ics';
export * from './external-calendar-colors';
export * from './task-relative-start';
export * from './task-status';
export * from './text-direction';
export * from './ai/ai-service';
export * from './ai/utils';
export * from './ai/types';
export * from './ai/catalog';
export * from './ai/model-list';
export * from './ai-config';
export * from './sqlite-schema';
export * from './task-sync-schema';
export * from './project-sync-schema';
export * from './section-sync-schema';
export * from './sqlite-adapter';
export * from './logger';
export * from './performance-log';
export * from './log-breadcrumbs';
export * from './pomodoro';
export * from './color-constants';
export * from './analytics-heartbeat';
export * from './dropbox-sync-utils';
export * from './dropbox';
export * from './backup-transfer';
export * from './todoist-import';
export * from './ticktick-import';
export * from './dgt-import';
export * from './omnifocus-import';
export * from './openpos-csv-import';
export * from './openpos-csv-export';
export * from './tasknotes-export';
export * from './mind-sweep';
export * from './focus-star';
export * from './focus-grouping';
export * from './context-color';
export * from './capture';
export * from './capture-session';
export * from './session-restore';
export * from './whisper-models';
export * from './import-apply';
export * from './import-diagnostics';
export * from './import-runner';
export * from './global-search-filter';
export * from './calendar-composer';
export * from './calendar-day-items';
export * from './calendar-feed';
export * from './calendar-push-scheduler';
export * from './date-draft';
export * from './i18n/i18n-locales';
export * from './theme-scheme';
export * from './startup-prompts';
export * from './area-sync-schema';
export * from './person-sync-schema';
export * from './import-source-reader';
export * from './settings-search-keys';
export * from './task-recurrence-fields';
export * from './shared-api-write-limits';
export * from './task-query';
