import { describe, expect, it } from 'vitest';
import { SUPPORTED_LANGUAGES } from './i18n-constants';
import { en } from './locales/en';
import { STARTER_SEED_STRINGS } from './starter-seed-strings';

// starter-seed-strings.ts is generated by scripts/i18n-locale-parity.ts, and `bun run
// i18n:check` is what catches a VALUE drifting out of date with the locale files. This is the
// cheaper half of the gate: shape. A generated table that is missing a language or a key
// degrades silently — getting-started-seed.ts just falls back to English — so it would ship a
// seed that no longer matches titles in that language and duplicates the tutorial tasks on
// re-seed. That failure never reaches i18n:check if someone hand-edits the file.
describe('generated starter seed strings', () => {
    const starterKeys = Object.keys(en).filter((key) => key.startsWith('starter.'));

    it('covers every supported language', () => {
        expect(Object.keys(STARTER_SEED_STRINGS).sort()).toEqual([...SUPPORTED_LANGUAGES].sort());
    });

    it.each(Object.keys(STARTER_SEED_STRINGS))('gives %s every starter key with real copy', (language) => {
        const strings = STARTER_SEED_STRINGS[language as keyof typeof STARTER_SEED_STRINGS];
        expect(Object.keys(strings).sort()).toEqual([...starterKeys].sort());
        expect(Object.values(strings).filter((value) => !value)).toEqual([]);
    });
});
