/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class',
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                background: "hsl(var(--background))",
                foreground: "hsl(var(--foreground))",
                card: "hsl(var(--card))",
                "card-foreground": "hsl(var(--card-foreground))",
                popover: "hsl(var(--popover))",
                "popover-foreground": "hsl(var(--popover-foreground))",
                primary: "hsl(var(--primary))",
                "primary-foreground": "hsl(var(--primary-foreground))",
                secondary: "hsl(var(--secondary))",
                "secondary-foreground": "hsl(var(--secondary-foreground))",
                muted: "hsl(var(--muted))",
                "muted-foreground": "hsl(var(--muted-foreground))",
                accent: "hsl(var(--accent))",
                "accent-foreground": "hsl(var(--accent-foreground))",
                destructive: "hsl(var(--destructive))",
                "destructive-foreground": "hsl(var(--destructive-foreground))",
                success: "hsl(var(--success))",
                "success-foreground": "hsl(var(--success-foreground))",
                warning: "hsl(var(--warning))",
                "warning-foreground": "hsl(var(--warning-foreground))",
                "focus-star": "hsl(var(--focus-star))",
                "focus-star-outline": "hsl(var(--focus-star-outline))",
                info: "hsl(var(--info))",
                "info-foreground": "hsl(var(--info-foreground))",
                "status-inbox": "hsl(var(--status-inbox))",
                "status-next": "hsl(var(--status-next))",
                "status-waiting": "hsl(var(--status-waiting))",
                "status-someday": "hsl(var(--status-someday))",
                "status-reference": "hsl(var(--status-reference))",
                "status-done": "hsl(var(--status-done))",
                border: "hsl(var(--border))",
                input: "hsl(var(--input))",
                ring: "hsl(var(--ring))",
            },
        },
    },
    plugins: [],
}
